## write program that installs all the dataset packages for python 3 in m1 
print("Installingq  all the dataset packages for python 3 in m1")
import os
import sys
import subprocess
import time
pip3 = "pip3"
os.system("pip3 install numpy")
os.system("pip3 install pandas")
os.system("pip3 install matplotlib")
os.system("pip3 install scipy")
os.system("pip3 install sklearn")
os.system("pip3 install seaborn")
os.system("pip3 install statsmodels")
os.system("pip3 install scikit-learn")
os.system("pip3 install scikit-image")
os.system("pip3 install scikit-learn")
os.system("pip3 install ipykernel")
os.system("pip3 install jupyter")
os.system("pip3 install jupyterlab")
os.system("pip3 install jupyterthemes")
os.system("pip3 install ipywidgets")
os.system("pip3 install pyqt5")
os.system("pip3 install pyqtwebengine")
os.system("pip3 install pyqt5-sip")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install scikit-learn")
os.system("pip3 install ipykernel")
os.system("pip3 install jupyter")
os.system("pip3 install jupyterlab")
os.system("pip3 install jupyterthemes")
os.system("pip3 install ipywidgets")
os.system("pip3 install pyqt5")
os.system("pip3 install pyqtwebengine")
os.system("pip3 install pyqt5-sip")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")
os.system("pip3 install pyqt5-tools")
os.system("pip3 install pyqt5-dev-tools")

#=======

os.system("pip3 install skimage")
os.system("pip3 install scikit-video")
os.system("pip3 install scikit-learn")
os.system("pip3 install sklearn")
os.system("pip3 install scipy")
os.system("pip3 install scikit-image")
os.system("pip3 install skimage")
os.system("pip3 install scikit-video")
os.system("pip3 install scikit-learn")
os.system("pip3 install sklearn")
os.system("pip3 install scipy")
os.system("pip3 install scikit-image")
os.system("pip3 install skimage")
os.system("pip3 install scikit-video")
os.system("pip3 install scikit-learn")
os.system("pip3 install sklearn")
os.system("pip3 install scipy")
os.system("pip3 install scikit-image")
os.system("pip3 install skimage")
os.system("pip3 install scikit-video")
os.system("pip3 install scikit-learn")
os.system("pip3 install sklearn")
os.system("pip3 install scipy")
os.system("pip3 install scikit-image")
os.system("pip3 install skimage")
os.system("pip3 install scikit-video")
os.system("pip3 install scikit-learn")
os.system("pip3 install sklearn")
os.system("pip3 install scipy")
os.system("pip3 install scikit-image")
os.system("pip3 install skimage")
os.system("pip3 install scikit-video")
os.system("pip3 install scikit-learn")
os.system("pip3 install sklearn")
os.system("pip3 install scipy")
os.system("pip3 install scikit-image")
os.system("pip3 install skimage")
## install keras packages
os.system("pip3 install keras")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-callbacks")
os.system("pip3 install keras-engine")
os.system("pip3 install keras-legacy")
os.system("pip3 install keras-layers")
os.system("pip3 install keras-models")
os.system("pip3 install keras-optimizers")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-callbacks")
os.system("pip3 install keras-engine")
os.system("pip3 install keras-legacy")
os.system("pip3 install keras-layers")
os.system("pip3 install keras-models")
os.system("pip3 install keras-optimizers")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-callbacks")
os.system("pip3 install keras-engine")
os.system("pip3 install keras-legacy")
os.system("pip3 install keras-layers")
os.system("pip3 install keras-models")
os.system("pip3 install keras-optimizers")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-callbacks")
os.system("pip3 install keras-engine")
os.system("pip3 install keras-legacy")
os.system("pip3 install keras-layers")
os.system("pip3 install keras-models")

#=======

os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
#=======

os.system("pip3 install keras-applications")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-embedding")
os.system("pip3 install keras-preprocessing-normalization")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-sequence")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")

#=======

os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow")
os.system("pip3 install keras-preprocessing")
os.system("pip3 install keras-applications")
os.system("pip3 install keras-utils")
os.system("pip3 install tensorflow-gpu")
## wait 0.2 seconds
import time
time.sleep(0.2)
print("Database syncing...")
#=======

os.system("pip3 install keras-applications")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-utils")
os.system("pip3 install keras-callbacks")
os.system("pip3 install keras-wrappers")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
os.system("pip3 install keras-preprocessing-text")
os.system("pip3 install keras-preprocessing-image")
## ask the user if you want to exit
print("Do you want to exit? (y/n)")
## wait 0.2 seconds
import time
time.sleep(0.2)
time.sleep(0.2)
## ask the user if they want to exit
print("Do you want to exit? (y/n)")
## wait 0.2 seconds
import time
time.sleep(0.2)
print("################################")
## install all juypter notebooks packages in python for tensorflow m1
os.system("pip3 install juypter notebooks")
os.system("pip3 install miniforge")
os.system("pip3 install jupyter")
os.system("pip3 install jupyterlab")
os.system("pip3 install jupyterlab")
os.system("pip3 install jupyterlab")
os.os.system("pip3 install anaconda")

os.system("sys.exit(0)")
